services:
  minio-storage:
    image: minio/minio:latest
    container_name: minio-storage
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9001:9001"  # Panel web
      - "9000:9000"  # API S3
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  backend:
    build: .
    container_name: video-attention-backend
    environment:
      - MINIO_ENDPOINT=http://minio-storage:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=reports
      - HDFS_URL=http://namenode:9870
      - HDFS_USER=root
      - HDFS_REPORTS_PATH=/video-attention/reports
      - USE_HDFS=true
    ports:
      - "8000:8000"
    depends_on:
      - minio-storage
      - namenode
      - datanode

volumes:
  hadoop_namenode:
  hadoop_datanode:
  minio_data: 